### ISSUE TITLE
Add description for each book

### ISSUE THREAD

**Issue by Onyelaudochukwuka** [EOEboh/Free-Software-Books#25]
Most people can't tell what exact book they need just from the name so adding a description other than the book name would give more context to each book, we can make use of the format below.

```
- [Book Name](link to book)

``
Description....
``
[Download](link to book) link to book
```

Also adding the link virtually rather than just a hyperlink will improve the accessibility.

**Comment by binadiegha** [comment]
While I think this is a great idea, I strongly believe this will make the list a little more complex, longer, and harder to find stuff. also, most people would already know the book they are looking for either by research or recommendation

**Comment by Onyelaudochukwuka** [comment]
<details>
<summary>React for Beginners</summary>
This is a book for react beginners that covers the basis of jsx, reacts hooks, custom hooks and state management.
</details>

Having something like this that takes the same length but hold more details is definitely a plus.

**Comment by binadiegha** [comment]
Now that you have this example, it looks good. if it is collapsed then it can work. that would mean we have to update the readme guide for contributing. @EOEboh

**Comment by EOEboh** [comment]
I personally feel not all contributors will want to add descriptions to every resource they add. 

As much as it’s a lovely feature, I want contributions to be as easy as the drop of a hat.

So we should specify it as an optional move.

**Comment by binadiegha** [comment]
I feel you. for consistency, maybe we should just stick to the existing pattern... so, say we close this issue?

**Comment by EOEboh** [comment]
No, here’s what we will do. 

We are going to specify it in the contribution guidelines, but only as an optional step. 

Something like adding (optional) in brackets.

**Comment by Klin-Coders** [comment]
The title of books is mostly descriptive, i suggest we do not add verbosity and pollute the resource directory with extended descriptions, the current setup is as straightforward as it gets

My opinion tho

**Comment by BaRzz007** [comment]
In my experience looking for resources, a short description will go a long way, so I won't have to read every book searching for what I'm looking for. 

For instance, if a book does good justice to a topic like OOP, having that description can help anybody wanting to read about OOP, the resource will then be interesting and easier to use.

**Comment by Onyelaudochukwuka** [comment]
> The title of books is mostly descriptive, i suggest we do not add verbosity and pollute the resource directory with extended descriptions, the current setup is as straightforward as it gets
> 
> My opinion tho

We're talking about books here the names are what the authors decide to call them so I don't see "descriptive" in a 3 letter sentence.

**Comment by EOEboh** [comment]
Whats the conclusion on this feature? If further discussion is needed, we can open a discussion tab for it

**Comment by binadiegha** [comment]
In the end I think this is a good idea. Maybe we can decide between this method or the solution provided on issue #30

**Comment by EOEboh** [comment]
Okay, I'm closing this issue now. Let every further related discussion be on #30
