### ISSUE TITLE
Add pull request and issue template.

### ISSUE THREAD

**Issue by Onyelaudochukwuka** [EOEboh/Free-Software-Books#26]
Add a pull request template to make creating an issue or pull request a breeze.

**Comment by binadiegha** [comment]
hello @Onyelaudochukwuka, thanks for your interest in contributing. @ibrahimraimi is already on the PR template, however, the Issue template is unassigned and we would be happy if you jumped on it😃

**Comment by Onyelaudochukwuka** [comment]
ok will do
