### ISSUE TITLE
Add PhP Resources 

### ISSUE THREAD

**Issue by adedejiibrahim7** [EOEboh/Free-Software-Books#43]
I intend to add some valuable free resources for PhP Devs, as nothing exists for PhP at the moment.

**Comment by EOEboh** [comment]
@adedejiibrahim7 please go ahead, we will be anticipating a pull request from you

**Comment by EOEboh** [comment]
@adedejiibrahim7 any update on this so far?

**Comment by binadiegha** [comment]
@adedejiibrahim7 how we looking on this issue?

**Comment by adedejiibrahim7** [comment]
Will soon make a PR
