### ISSUE TITLE
C programming book

### ISSUE THREAD

**Issue by falsharion** [EOEboh/Free-Software-Books#55]
## The C Programming Language (2nd Edition) by Brian W. Kernighan, Dennis M. Ritchie
This book is meant to help the reader learn how to program in C. It contains a tutorial introduction to get new users started as soon as possible, separate chapters on each major feature, and a reference manual.

**Comment by binadiegha** [comment]
Hello @falsharion, please proceed to make a PR. you can add it to the `.../dev-books/others` category.

**Comment by binadiegha** [comment]
@falsharion greetings to you... How we looking? 😁

**Comment by EOEboh** [comment]
@falsharion  what's the status of this issue?
